-- Author: Nehal Parsekar
-- Roll No: 1942

CREATE TABLE Users(
	id VARCHAR(256) PRIMARY KEY,
	userName VARCHAR(32) NOT NULL,
	userAddress VARCHAR(128) NOT NULL,
	userYear INT NOT NULL,
	userGender VARCHAR(8) NOT NULL,
	userContact VARCHAR(16) NOT NULL,
	userEmail VARCHAR(256),
	userPassword VARCHAR(256),
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL,
	userType VARCHAR(8) NOT NULL
);

CREATE TABLE States(
	id VARCHAR(256) PRIMARY KEY,
	stateName VARCHAR(32) NOT NULL,
	adminId VARCHAR(256) NOT NULL REFERENCES Users(id),
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Stations(
	id VARCHAR(256) PRIMARY KEY,
	stateId VARCHAR(256) NOT NULL REFERENCES States(id),
	adminId VARCHAR(256) NOT NULL REFERENCES Users(id),
	stationName VARCHAR(32) NOT NULL,
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Trains(
	id VARCHAR(256) PRIMARY KEY,
	trainName VARCHAR(32) NOT NULL,
	acSeats INTEGER NOT NULL,
	generalSeats INTEGER NOT NULL,
	adminId VARCHAR(256) NOT NULL REFERENCES Users(id),
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Schedules(
	id VARCHAR(256) PRIMARY KEY,
	scheduleName VARCHAR(32) NOT NULL,
	adminId VARCHAR(256) NOT NULL REFERENCES Users(id),
	arrival TIME NOT NULL,
	departure TIME NOT NULL,
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE Routes(
	id VARCHAR(256) PRIMARY KEY,
	routeName VARCHAR(64) NOT NULL,
	routeFare FLOAT NOT NULL,
	adminId VARCHAR(256) NOT NULL REFERENCES Users(id),
	sStationId VARCHAR(256) NOT NULL REFERENCES Stations(id),
	dStationId VARCHAR(256) NOT NULL REFERENCES Stations(id),
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE RouteSchedule(
	id VARCHAR(256) PRIMARY KEY,
	routeId VARCHAR(256) NOT NULL REFERENCES Routes(id),
	scheduleId VARCHAR(256) NOT NULL REFERENCES Schedules(id),
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

CREATE TABLE RouteTrain(
	id VARCHAR(256) PRIMARY KEY,
	routeId VARCHAR(256) NOT NULL REFERENCES Routes(id),
	trainId VARCHAR(256) NOT NULL REFERENCES Trains(id),
	createdAt TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP NOT NULL
);

SHOW TABLES;

DROP TABLE Schedule;

DELETE FROM States WHERE 1=1;

SELECT * FROM Schedules;

DESC Users;











